### ISSUE TITLE
error about load ani

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [thetrik/VbPng#1]
my user id in vbforum is Black_Storm.

i selected some ani files for mouse pointer but some of them loaded and some of them error about "invalid picture" so what kind ani support?!!! i think this error maybe happen for some of ico or cur files too.

and can u add 2 support format too about animted pictures?

important is apng format(animated png format and animated gif format) but apng is better,i can load apng in vb6 but with some user controls but i like use in this add ins too

**Comment by thetrik** [comment]
Thank you for testing. What's the ANI doesn't work? Can you attach a file?

**Comment by wwwbarnamehadotnet** [comment]
hi i recorded screen from my use :

most times this error :
![2](https://user-images.githubusercontent.com/12879605/154866287-7011f6b7-d3f9-49cb-bd93-9da65ab33a2e.gif)
some times when i select that ani files work some times same files not work with that error .
this error is about other ani files too like theme.
this error happen when i select png or etc too for image box or other controls :

i attached that ani files too.
[demo.zip](https://github.com/thetrik/VbPng/files/8105033/demo.zip)


 
and some times i see this error  too :
![error](https://user-images.githubusercontent.com/12879605/154866337-c88eaf63-b43c-4c1c-9421-6a3dd5539140.png)
 
i have a question too about possible to load icon without lose quality, my means in this recorded screen,because i select icon but after run quality will be lose:
![1](https://user-images.githubusercontent.com/12879605/154866371-72261e6e-b0dd-4a5f-a899-4dc37f10c302.gif)

**Comment by thetrik** [comment]
> hi i recorded screen from my use :
> 
> most times this error : ![2](https://user-images.githubusercontent.com/12879605/154866287-7011f6b7-d3f9-49cb-bd93-9da65ab33a2e.gif) some times when i select that ani files work some times same files not work with that error . this error is about other ani files too like theme. this error happen when i select png or etc too for image box or other controls :
> 
> i attached that ani files too. [demo.zip](https://github.com/thetrik/VbPng/files/8105033/demo.zip)
> 
> and some times i see this error too : ![error](https://user-images.githubusercontent.com/12879605/154866337-c88eaf63-b43c-4c1c-9421-6a3dd5539140.png)
> 
> i have a question too about possible to load icon without lose quality, my means in this recorded screen,because i select icon but after run quality will be lose: ![1](https://user-images.githubusercontent.com/12879605/154866371-72261e6e-b0dd-4a5f-a899-4dc37f10c302.gif)

You have the broken files (the RIFF chunk size is incorrect).

[demo.zip](https://github.com/thetrik/VbPng/files/8106712/demo.zip)

Regarding to the second question - please attach an example.

**Comment by wwwbarnamehadotnet** [comment]
> **You have the broken files (the RIFF chunk size is incorrect).**

If you mean that the files have problems, many of them are in the famous software "Design of animated cursors",that files open without any problems in these softwares,I just randomly tested several files, if I want to Every file I open may have some of them unusable.

in this sample i tested that ani files with others apps without problem:

![11](https://user-images.githubusercontent.com/12879605/155046823-52457d08-3333-4314-872d-ee7d1f8e2488.gif)

it is only in using this add-ins that I have a problem, "Of course you noticed that I said before that most of the time it gives an error and sometimes it works correctly?" While the same file that gave the error sometimes opens and sometimes gives an error, in this case, how is it possible that the file is corrupted? i think something is wrong in add-ins , i showed another error too.

> Regarding to the second question - please attach an example.

The last image I posted in the previous article was an example,this is another attach :

![22](https://user-images.githubusercontent.com/12879605/155047279-c41e2df3-ab6a-449f-8077-5337d4ab8e4d.gif)
possible to can keep that orginal quality after open?

**Comment by thetrik** [comment]
> If you mean that the files have problems, many of them are in the famous software "Design of animated cursors",that files open without any problems in these softwares,I just randomly tested several files, if I want to Every file I open may have some of them unusable.

Yes, your previous attached files have the bad RIFF structure. The Add-in requires valid RIFF structure because it uses CreateIconFromResourceEx function which doesn't accept broken files. Did you try the files i attached in the previous post? They are fixed and work good but now i'll know which program should not be used for creating cursors.



> The last image I posted in the previous article was an example,this is another attach :

I meant attach the problem icon not animation.
